name: jgregorybarton
favicon: null
layout_spectrum: 0.75369
typography_spectrum: 0.26024
title: Creation in Real Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0c78e'
    - '#b26e25'
    - '#000008'
    - '#5c392f'
    - '#98b0d3'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
