name: jgregorybarton
favicon: null
layout_spectrum: 0.13985076895914972
typography_spectrum: 0.5483258641324937
title: Creation in Real Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.44679206889122725
  lightness: 0.5167772846762091
  saturation: 0.06405119854025543
  rhythmicContrast: 0.2284306043293327
purpose: []
