typography_spectrum: 0.26024
color:
  brandColors:
    - '#e0c78e'
    - '#b26e25'
    - '#000008'
    - '#5c392f'
    - '#98b0d3'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75369
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: j Gregory Barton
  email: jgregorybarton@gmail.com
name: jgregorybarton
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Creation in Real Life
purpose: []
